[theme]
base = "dark"
primaryColor = "#C8A464"
backgroundColor = "#111210"
secondaryBackgroundColor = "#1A1B19"
textColor = "#E7E4DA"
font = "sans-serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[server]
enableStaticServing = true
